module.exports = {
  mySidebar: [
    'overview',
    'release-notes',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'doc',
        id: 'installation/overview',
      },
      collapsed: true,
      items: [
        'installation/preparing-the-installation',
        'installation/new-installation',
        'installation/upgrade',
        'installation/bis-mam-installation',
        'installation/installation-reference',
        'installation/installation-parameters-worksheet',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {
        type: 'doc',
        id: 'configuration/overview',
      },
      collapsed: true,
      items: [
        'configuration/configuration-settings',
        'configuration/page-one-settings',
        'configuration/page-two-settings',
        'configuration/console-message-display-level',
        'configuration/configure-bis',
        'configuration/configure-jors',
        'configuration/additional-settings',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {
        type: 'doc',
        id: 'operations/overview',
      },
      collapsed: true,
      items: [
        'operations/components',
        'operations/operating-the-lsam',
        'operations/commands',
      ],
    },
      'additional-features',
      'file-transfer',
      'support-data-collector',
      'smamsc',
      'ftpapi',
      {
        type: 'category',
        label: 'Reference',
        link: {
          type: 'doc',
          id: 'reference/overview',
        },
        collapsed: true,
        items: [
          'reference/lsam-job-messages',
          'reference/lsam-system-console-messages',
          'reference/lmam-messages',
          'reference/bis-mam-messages',
          'reference/jors-messages',
          'reference/xfrtcp-messages',
          'reference/file-transfer-server-messages',
          'reference/file-transfer-agent-messages',
          'reference/known-issues',
        ],
      },
  ],
};
